apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmgr-config
spec:
  replicas: 1
  selector:
    matchLabels:
      name: alertmgr-config
  template:
    metadata:
      labels:
        name: alertmgr-config
    spec:
      serviceAccountName: alertmgr-config
      containers:
        - name: alertmgr-config
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - alertmgr-config
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "alertmgr-config"
