apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmgr-config
spec:
  replicas: 1
  selector:
    matchLabels:
      name: alertmgr-config
  template:
    metadata:
      labels:
        name: alertmgr-config
    spec:
      serviceAccountName: alertmgr-config
      containers:
        - name: alertmgr-config
          image: platform9/alertmgr-config
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "alertmgr-config"
