apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmgrcfg-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: alertmgrcfg-operator
  template:
    metadata:
      labels:
        name: alertmgrcfg-operator
    spec:
      serviceAccountName: alertmgrcfg-operator
      containers:
        - name: alertmgr-config
          image: platform9/alertmgrcfg-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "alertmgrcfg-operator"
