kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alertmgr-config
subjects:
- kind: ServiceAccount
  name: alertmgr-config
roleRef:
  kind: Role
  name: alertmgr-config
  apiGroup: rbac.authorization.k8s.io
