kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alertmgrcfg-operator-deployer
subjects:
- kind: ServiceAccount
  name: alertmgrcfg-operator
  namespace: pf9-operators
roleRef:
  kind: ClusterRole
  name: alertmgrcfg-operator-deployer
  apiGroup: rbac.authorization.k8s.io
