apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alertmgrcfg-operator-deployer
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - services
  verbs:
  - '*'
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - monitoring.pf9.io
  resources:
  - '*'
  verbs:
  - '*'
